name: dart_install
description: Command-line application to install the Dart SDK.
version: 0.9.9
homepage: https://github.com/wiremoons/dart_install

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.3.8
  args: ^2.3.1
  dav: ^0.2.0
  http: ^1.0.0
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
