name: dart_install
description: Command-line application to install the Dart SDK.
version: 0.2.3
homepage: https://github.com/wiremoons/dart_install

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.3.1
  http: ^0.13.5
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
